[package]
name = "panctl"
version = "0.11.0"
edition = "2021"
description = "Control tool for pantalaimon via D-Bus"
license = "Apache-2.0"

[[bin]]
name = "panctl"
path = "src/main.rs"

[build-dependencies]
clap = { workspace = true }
clap_mangen = { workspace = true }

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }
zbus = { version = "4", default-features = false, features = ["tokio"] }
rpassword = { workspace = true }
